name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update infrastructure repository
        env:
          GH_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone infrastructure repo
          git clone https://x-access-token:${GH_TOKEN}@github.com/ejpolicarpio/github-etl-infrastructure.git infra

          cd infra

          # Update image tag in values-dev.yaml
          NEW_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d: -f2)
          sed -i "s|tag:.*|tag: ${NEW_TAG}|g" helm/github-etl/values-dev.yaml

          # Commit and push
          git add helm/github-etl/values-dev.yaml
          git commit -m "Update dev image to ${NEW_TAG}" || exit 0
          git push origin main